name: .NET MAUI Build

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Install .NET MAUI Android workload
        run: dotnet workload install maui-android

      - name: Install dependencies
        run: dotnet restore

      - name: Build iOS project
        run: dotnet build -t:Build -restore -p:Configuration=Release -p:Platform=iPhone -p:IosBuildSystem=msbuild

      - name: Build Android project
        run: dotnet build -t:Build -restore -p:Configuration=Release -p:Platform=Android

      # Add additional steps here such as running tests or packaging the app for distribution
